version: "3.8"

services:
  database:
    container_name: database
    image: postgres:alpine
    restart: always
    # environment:
    #   - POSTGRES_USER=postgres
    #   - POSTGRES_PASSWORD=12345
    #   - POSTGRES_DB=auth
    env_file:
      - .env
    ports:
      - 6500:5432
    volumes:
      - db:/var/lib/postgresql/data
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    volumes:
      - .:/usr/src/app
    depends_on:
      - database
    env_file:
      - .env

volumes:
  db:
